Extract description, riskfactors and evaluationdate from the payload
palladiumkenya/openmrs-module-kenyaemr-machine-learning pull request #19
Opened 2022-07-26 12:55 UTC by PatrickWaweru

[Extract description, riskfactors and evaluationdate from the payload

2022-07-26 17:34 UTC, ojwanganto requested changes

2022-07-26 17:34 UTC, ojwanganto commented on api/src/main/java/org/openmrs/module/kenyaemrml/util/MLDataExchange.java
> +									description = person.get("description").asText();
we can use personObject instead of person. What do you think?

2022-07-27 05:23 UTC, PatrickWaweru commented on api/src/main/java/org/openmrs/module/kenyaemrml/util/MLDataExchange.java
> +									description = person.get("description").asText();
hehe yes i noticed the name person has a special meaning in openMRS

2022-07-27 05:24 UTC, PatrickWaweru commented on api/src/main/java/org/openmrs/module/kenyaemrml/util/MLDataExchange.java
> +									description = person.get("description").asText();
Fixed: https://github.com/palladiumkenya/openmrs-module-kenyaemr-machine-learning/pull/19/commits/cf4d20476434bd2053c8c6a6a0e59c6ad655c99c

2022-07-27 07:29 UTC, merged