Removed some vars and Added new Feb 2024 model
palladiumkenya/openmrs-module-kenyaemr-machine-learning pull request #84
Opened 2024-02-15 08:59 UTC by PatrickWaweru

Removed some vars and Added new Feb 2024 model

2024-02-15 09:06 UTC, ojwanganto requested changes

2024-02-15 09:06 UTC, ojwanganto commented on omod/src/main/java/org/openmrs/module/kenyaemrml/web/controller/MachineLearningRestController.java
> +			JSONObject profile = MLUtils.getIITFacilityProfile("FacilityCode", facilityMflCode, MLUtils.getIITFacilityCutOffs());
Do we have different facility profiles for HTS and IIT?

2024-02-15 09:06 UTC, ojwanganto commented on pom.xml
> +	<version>1.3.7</version>
are we releasing this or it should be a snapshot?

2024-02-15 09:06 UTC, ojwanganto commented on api/src/main/resources/liquibase.xml
> +            <columnExists tableName="kenyaemr_ml_patient_risk_score" columnName="n_hvl_threeyears"/>
Are we doing this once, or every time the task runs it is computed again? You may thing of just computing what doesn't exist to cut down on processing time.

2024-02-15 09:50 UTC, PatrickWaweru commented on omod/src/main/java/org/openmrs/module/kenyaemrml/web/controller/MachineLearningRestController.java
> +			JSONObject profile = MLUtils.getIITFacilityProfile("FacilityCode", facilityMflCode, MLUtils.getIITFacilityCutOffs());
Yes. They are currently different but they will soon make them the same.

2024-02-15 09:59 UTC, PatrickWaweru commented on pom.xml
> +	<version>1.3.7</version>
https://github.com/palladiumkenya/openmrs-module-kenyaemr-machine-learning/pull/84/commits/2b3425c01c479957b7b28260d9c44ccdc79dc07d

Done

2024-02-15 15:08 UTC, njorocs approved these changes
Looks okay

2024-02-15 20:16 UTC, ojwanganto commented on api/src/main/resources/liquibase.xml
> +            <columnExists tableName="kenyaemr_ml_patient_risk_score" columnName="n_hvl_threeyears"/>
What happens in subsequent visits? how is the logic? sorry to comment late

2024-02-16 08:58 UTC, PatrickWaweru commented on api/src/main/resources/liquibase.xml
> +            <columnExists tableName="kenyaemr_ml_patient_risk_score" columnName="n_hvl_threeyears"/>
The variables that require computation mainly involve averages. These have to be computed every call. But the call only happens if it is a new visit and a greencard has been filled. The user has to be checked in. Otherwise we just pick the data from the DB without any computations. The model has also been reduced in size from the previous 80MB to around 7MB so right now it has very little- effect on performance.

2024-02-16 10:05 UTC, ojwanganto commented on api/src/main/resources/liquibase.xml
> +            <columnExists tableName="kenyaemr_ml_patient_risk_score" columnName="n_hvl_threeyears"/>
great

2024-02-16 10:07 UTC, ojwanganto approved these changes

2024-02-16 10:07 UTC, merged